import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import localFont from "next/font/local";
import HeaderNavbar from "../components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
